/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CuecMappingRouteImport } from './routes/cuec-mapping'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkpapersIndexRouteImport } from './routes/workpapers/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ControlsIndexRouteImport } from './routes/controls.index'
import { Route as WorkpapersGenerateRouteImport } from './routes/workpapers/generate'
import { Route as WorkpapersIdRouteImport } from './routes/workpapers/$id'
import { Route as InviteAcceptRouteImport } from './routes/invite/accept'
import { Route as ControlsLayoutRouteImport } from './routes/controls.layout'
import { Route as ControlsCreateRouteImport } from './routes/controls/create'
import { Route as WorkpapersReportsIdRouteImport } from './routes/workpapers/reports/$id'
import { Route as WorkpapersIdEditRouteImport } from './routes/workpapers/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CuecMappingRoute = CuecMappingRouteImport.update({
  id: '/cuec-mapping',
  path: '/cuec-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkpapersIndexRoute = WorkpapersIndexRouteImport.update({
  id: '/workpapers/',
  path: '/workpapers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsIndexRoute = ControlsIndexRouteImport.update({
  id: '/controls/',
  path: '/controls/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkpapersGenerateRoute = WorkpapersGenerateRouteImport.update({
  id: '/workpapers/generate',
  path: '/workpapers/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkpapersIdRoute = WorkpapersIdRouteImport.update({
  id: '/workpapers/$id',
  path: '/workpapers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteAcceptRoute = InviteAcceptRouteImport.update({
  id: '/invite/accept',
  path: '/invite/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsLayoutRoute = ControlsLayoutRouteImport.update({
  id: '/controls/layout',
  path: '/controls/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsCreateRoute = ControlsCreateRouteImport.update({
  id: '/controls/create',
  path: '/controls/create',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkpapersReportsIdRoute = WorkpapersReportsIdRouteImport.update({
  id: '/workpapers/reports/$id',
  path: '/workpapers/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkpapersIdEditRoute = WorkpapersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => WorkpapersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cuec-mapping': typeof CuecMappingRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/exceptions': typeof ExceptionsRoute
  '/login': typeof LoginRoute
  '/controls/create': typeof ControlsCreateRoute
  '/controls/layout': typeof ControlsLayoutRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/workpapers/$id': typeof WorkpapersIdRouteWithChildren
  '/workpapers/generate': typeof WorkpapersGenerateRoute
  '/controls': typeof ControlsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workpapers': typeof WorkpapersIndexRoute
  '/workpapers/$id/edit': typeof WorkpapersIdEditRoute
  '/workpapers/reports/$id': typeof WorkpapersReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cuec-mapping': typeof CuecMappingRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/exceptions': typeof ExceptionsRoute
  '/login': typeof LoginRoute
  '/controls/create': typeof ControlsCreateRoute
  '/controls/layout': typeof ControlsLayoutRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/workpapers/$id': typeof WorkpapersIdRouteWithChildren
  '/workpapers/generate': typeof WorkpapersGenerateRoute
  '/controls': typeof ControlsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/workpapers': typeof WorkpapersIndexRoute
  '/workpapers/$id/edit': typeof WorkpapersIdEditRoute
  '/workpapers/reports/$id': typeof WorkpapersReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cuec-mapping': typeof CuecMappingRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/exceptions': typeof ExceptionsRoute
  '/login': typeof LoginRoute
  '/controls/create': typeof ControlsCreateRoute
  '/controls/layout': typeof ControlsLayoutRoute
  '/invite/accept': typeof InviteAcceptRoute
  '/workpapers/$id': typeof WorkpapersIdRouteWithChildren
  '/workpapers/generate': typeof WorkpapersGenerateRoute
  '/controls/': typeof ControlsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/workpapers/': typeof WorkpapersIndexRoute
  '/workpapers/$id/edit': typeof WorkpapersIdEditRoute
  '/workpapers/reports/$id': typeof WorkpapersReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cuec-mapping'
    | '/dashboard'
    | '/evidence'
    | '/exceptions'
    | '/login'
    | '/controls/create'
    | '/controls/layout'
    | '/invite/accept'
    | '/workpapers/$id'
    | '/workpapers/generate'
    | '/controls'
    | '/settings'
    | '/workpapers'
    | '/workpapers/$id/edit'
    | '/workpapers/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cuec-mapping'
    | '/dashboard'
    | '/evidence'
    | '/exceptions'
    | '/login'
    | '/controls/create'
    | '/controls/layout'
    | '/invite/accept'
    | '/workpapers/$id'
    | '/workpapers/generate'
    | '/controls'
    | '/settings'
    | '/workpapers'
    | '/workpapers/$id/edit'
    | '/workpapers/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/cuec-mapping'
    | '/dashboard'
    | '/evidence'
    | '/exceptions'
    | '/login'
    | '/controls/create'
    | '/controls/layout'
    | '/invite/accept'
    | '/workpapers/$id'
    | '/workpapers/generate'
    | '/controls/'
    | '/settings/'
    | '/workpapers/'
    | '/workpapers/$id/edit'
    | '/workpapers/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CuecMappingRoute: typeof CuecMappingRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRoute
  ExceptionsRoute: typeof ExceptionsRoute
  LoginRoute: typeof LoginRoute
  ControlsCreateRoute: typeof ControlsCreateRoute
  ControlsLayoutRoute: typeof ControlsLayoutRoute
  InviteAcceptRoute: typeof InviteAcceptRoute
  WorkpapersIdRoute: typeof WorkpapersIdRouteWithChildren
  WorkpapersGenerateRoute: typeof WorkpapersGenerateRoute
  ControlsIndexRoute: typeof ControlsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  WorkpapersIndexRoute: typeof WorkpapersIndexRoute
  WorkpapersReportsIdRoute: typeof WorkpapersReportsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuec-mapping': {
      id: '/cuec-mapping'
      path: '/cuec-mapping'
      fullPath: '/cuec-mapping'
      preLoaderRoute: typeof CuecMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workpapers/': {
      id: '/workpapers/'
      path: '/workpapers'
      fullPath: '/workpapers'
      preLoaderRoute: typeof WorkpapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/': {
      id: '/controls/'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workpapers/generate': {
      id: '/workpapers/generate'
      path: '/workpapers/generate'
      fullPath: '/workpapers/generate'
      preLoaderRoute: typeof WorkpapersGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workpapers/$id': {
      id: '/workpapers/$id'
      path: '/workpapers/$id'
      fullPath: '/workpapers/$id'
      preLoaderRoute: typeof WorkpapersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/accept': {
      id: '/invite/accept'
      path: '/invite/accept'
      fullPath: '/invite/accept'
      preLoaderRoute: typeof InviteAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/layout': {
      id: '/controls/layout'
      path: '/controls/layout'
      fullPath: '/controls/layout'
      preLoaderRoute: typeof ControlsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls/create': {
      id: '/controls/create'
      path: '/controls/create'
      fullPath: '/controls/create'
      preLoaderRoute: typeof ControlsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workpapers/reports/$id': {
      id: '/workpapers/reports/$id'
      path: '/workpapers/reports/$id'
      fullPath: '/workpapers/reports/$id'
      preLoaderRoute: typeof WorkpapersReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workpapers/$id/edit': {
      id: '/workpapers/$id/edit'
      path: '/edit'
      fullPath: '/workpapers/$id/edit'
      preLoaderRoute: typeof WorkpapersIdEditRouteImport
      parentRoute: typeof WorkpapersIdRoute
    }
  }
}

interface WorkpapersIdRouteChildren {
  WorkpapersIdEditRoute: typeof WorkpapersIdEditRoute
}

const WorkpapersIdRouteChildren: WorkpapersIdRouteChildren = {
  WorkpapersIdEditRoute: WorkpapersIdEditRoute,
}

const WorkpapersIdRouteWithChildren = WorkpapersIdRoute._addFileChildren(
  WorkpapersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CuecMappingRoute: CuecMappingRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRoute,
  ExceptionsRoute: ExceptionsRoute,
  LoginRoute: LoginRoute,
  ControlsCreateRoute: ControlsCreateRoute,
  ControlsLayoutRoute: ControlsLayoutRoute,
  InviteAcceptRoute: InviteAcceptRoute,
  WorkpapersIdRoute: WorkpapersIdRouteWithChildren,
  WorkpapersGenerateRoute: WorkpapersGenerateRoute,
  ControlsIndexRoute: ControlsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  WorkpapersIndexRoute: WorkpapersIndexRoute,
  WorkpapersReportsIdRoute: WorkpapersReportsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
